name: "test-build-macos"
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #   - 'flake.lock'
  #   - 'flake.nix'
  #   - 'hosts/laptop/**'
  #   - 'darwin/**'
  #   - 'home/**'
  #   - '.github/workflows/build-macos'
jobs:
  build_macos:
    runs-on: macos-14
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Check Nix Flake Inputs
      uses: DeterminateSystems/flake-checker-action@main
      with:
        send-statistics: false
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cache Nix Build
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Successful Build
      run: |
        cp /etc/nix/nix.conf ~/.config/nix/nix.conf
        sudo rm -rf /etc/zshenv /etc/nix/nix.conf
        sed -i '' -E 's "mm "runner g' hosts/laptop/users.nix home/home.nix
        sed -i '' -E 's \/mm \/runner g' hosts/laptop/users.nix home/home.nix
        sed -i '' -E 's users\.mm users\.runner g' flake.nix
        nix run nix-darwin -- switch --flake .#macbook
