name: "macos-build"
on:
  push:
    branches: [ dev ]
    paths:
    - 'flake.lock'
    - 'flake.nix'
    - 'hosts/laptop/**'
    - 'common/darwin/**'
    - 'common/home/**'
    - '.github/workflows/**'
jobs:
  build_and_deploy:
    runs-on: macos-14
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Check Nix Flake Inputs
      uses: DeterminateSystems/flake-checker-action@main
      with:
        send-statistics: false
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cache Nix Build
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Build Completes Successfully
      run: |
        sudo rm -rf /etc/zshenv
        nix run nix-darwin -- switch --flake .#macbook
