name: "deploy-flake"
on:
  push:
    branches: [ main ]
    paths:
    - 'flake.lock'
    - 'flake.nix'
    - 'hosts/media/**'
    - 'secrets/**'
    - 'common/nixos/**'
    - '.github/workflows/build-nixos.yml'
    - '.github/workflows/deploy-nixos.yml'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Check Nix Flake Inputs
      uses: DeterminateSystems/flake-checker-action@main
      with:
        send-statistics: false
    - name: Install Tailscale
      uses: tailscale/github-action@main
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        args: --ssh
        tags: tag:github
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cache Nix Build
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Deploy Nix Flake
      run: |
        nix run github:serokell/deploy-rs .#media
